FROM registry.access.redhat.com/ubi9/nodejs-20:latest

USER 0
WORKDIR /opt/app-root/src

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY src ./src
COPY public ./public

RUN chown -R 1001:0 /opt/app-root/src
USER 1001

ENV PORT=3000
EXPOSE 3000

CMD ["node", "src/server.js"]
